### ISSUE TITLE
Cannot select text in the Speakers / Alternates cols

### ISSUE THREAD

**Issue by krisbulman** [Lullabot/rosterfarian#6]
Not being able to select text in the speakers / alternate columns on the roster page agitates my OCD.

The following style is the offender: 

``` CSS
.caja-guest-0___ .site-name a {
  width: 100%;
  height: 100%;
  ...
}
```
